;;; w3m-load.el --- automatically extracted autoload
;;
;; This file should be generated by make in emacs-w3m source directory.
;;
;;; Code:

(provide 'w3m-load)

;;;### (autoloads nil "bookmark-w3m" "bookmark-w3m.el" (19648 52975
;;;;;;  0 0))
;;; Generated autoloads from bookmark-w3m.el

(autoload 'bookmark-w3m-bookmark-jump "bookmark-w3m" "\
Default bookmark handler for w3m buffers.

\(fn BOOKMARK)" nil nil)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "bookmark-w3m" '("bookmark-w3m-")))

;;;***

;;;### (autoloads nil "mime-w3m" "mime-w3m.el" (22866 65015 0 0))
;;; Generated autoloads from mime-w3m.el

(autoload 'mime-w3m-preview-text/html "mime-w3m" "\


\(fn ENTITY SITUATION)" nil nil)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "mime-w3m" '("mime-w3m-")))

;;;***

;;;### (autoloads nil "nnshimbun" "shimbun/nnshimbun.el" (23493 12191
;;;;;;  0 0))
;;; Generated autoloads from shimbun/nnshimbun.el

(autoload 'gnus-summary-refer-shimbun-article "nnshimbun" "\
Show a shimbun article pointed to by the given URL.

\(fn URL)" t nil)

(autoload 'gnus-group-make-shimbun-group "nnshimbun" "\
Create a new nnshimbun group.
The user will be prompted for a SERVER name and a GROUP name.  When
this command is called with a prefix argument, it makes an ephemeral
shimbun group.

\(fn SERVER GROUP &optional EPHEMERAL)" t nil)

(autoload 'gnus-group-make-shimbun-groups "nnshimbun" "\
Create all nnshimbun groups prepared for SERVER.

\(fn SERVER)" t nil)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "nnshimbun" '("nnshimbun-")))

;;;***

;;;### (autoloads nil "octet" "octet.el" (22676 10130 0 0))
;;; Generated autoloads from octet.el

(autoload 'octet-buffer "octet" "\
View octet-stream content according to `octet-type-filter-alist'.
Optional NAME is the filename.
If optional CONTENT-TYPE is specified, it is used for type guess.

\(fn &optional NAME CONTENT-TYPE)" t nil)

(autoload 'octet-find-file "octet" "\
Find FILE with octet-stream decoding.

\(fn FILE)" t nil)

(autoload 'mime-preview-octet "octet" "\
A method for mime-view to preview octet message.

\(fn ENTITY SITUATION)" nil nil)

(autoload 'mime-view-octet "octet" "\
A method for mime-view to display octet message.

\(fn ENTITY SITUATION)" nil nil)

(autoload 'octet-mime-setup "octet" "\
Octet setting for MIME module.

\(fn)" nil nil)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "octet" '("mime-" "octet-" "w3m-about-octet-attachments")))

;;;***

;;;### (autoloads nil "sb-2ch" "shimbun/sb-2ch.el" (17099 7485 0
;;;;;;  0))
;;; Generated autoloads from shimbun/sb-2ch.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-2ch" '("shimbun-2ch-")))

;;;***

;;;### (autoloads nil "sb-airs" "shimbun/sb-airs.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-airs.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-airs" '("shimbun-airs-")))

;;;***

;;;### (autoloads nil "sb-aljazeera" "shimbun/sb-aljazeera.el" (18767
;;;;;;  27322 0 0))
;;; Generated autoloads from shimbun/sb-aljazeera.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-aljazeera" '("shimbun-aljazeera-" "sb-aljazeera-wash-article")))

;;;***

;;;### (autoloads nil "sb-arch-bluegate" "shimbun/sb-arch-bluegate.el"
;;;;;;  (18197 61166 0 0))
;;; Generated autoloads from shimbun/sb-arch-bluegate.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-arch-bluegate" '("shimbun-arch-bluegate-")))

;;;***

;;;### (autoloads nil "sb-asahi" "shimbun/sb-asahi.el" (23431 15846
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-asahi.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-asahi" '("shimbun-asahi-")))

;;;***

;;;### (autoloads nil "sb-asahi-html" "shimbun/sb-asahi-html.el"
;;;;;;  (18197 61166 0 0))
;;; Generated autoloads from shimbun/sb-asahi-html.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-asahi-html" '("shimbun-asahi-html-prefer-text-plain")))

;;;***

;;;### (autoloads nil "sb-asahi-mytown" "shimbun/sb-asahi-mytown.el"
;;;;;;  (18197 61166 0 0))
;;; Generated autoloads from shimbun/sb-asahi-mytown.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-asahi-mytown" '("shimbun-asahi-mytown-")))

;;;***

;;;### (autoloads nil "sb-atmarkit" "shimbun/sb-atmarkit.el" (19666
;;;;;;  14148 0 0))
;;; Generated autoloads from shimbun/sb-atmarkit.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-atmarkit" '("shimbun-atmarkit-")))

;;;***

;;;### (autoloads nil "sb-atom" "shimbun/sb-atom.el" (19888 58288
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-atom.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-atom" '("shimbun-atom-")))

;;;***

;;;### (autoloads nil "sb-atom-hash" "shimbun/sb-atom-hash.el" (19888
;;;;;;  58288 0 0))
;;; Generated autoloads from shimbun/sb-atom-hash.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-atom-hash" '("shimbun-atom-")))

;;;***

;;;### (autoloads nil "sb-bbc" "shimbun/sb-bbc.el" (18219 1500 0
;;;;;;  0))
;;; Generated autoloads from shimbun/sb-bbc.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-bbc" '("shimbun-bbc-")))

;;;***

;;;### (autoloads nil "sb-bbdb-ml" "shimbun/sb-bbdb-ml.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-bbdb-ml.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-bbdb-ml" '("shimbun-bbdb-ml-")))

;;;***

;;;### (autoloads nil "sb-cgi-board" "shimbun/sb-cgi-board.el" (19122
;;;;;;  51388 0 0))
;;; Generated autoloads from shimbun/sb-cgi-board.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-cgi-board" '("shimbun-cgi-board-")))

;;;***

;;;### (autoloads nil "sb-chise" "shimbun/sb-chise.el" (20487 33066
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-chise.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-chise" '("shimbun-chise-")))

;;;***

;;;### (autoloads nil "sb-cnet" "shimbun/sb-cnet.el" (19666 14148
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-cnet.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-cnet" '("shimbun-cnet-")))

;;;***

;;;### (autoloads nil "sb-cnet-jp" "shimbun/sb-cnet-jp.el" (19666
;;;;;;  14148 0 0))
;;; Generated autoloads from shimbun/sb-cnet-jp.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-cnet-jp" '("shimbun-cnet-jp-")))

;;;***

;;;### (autoloads nil "sb-cnn-jp" "shimbun/sb-cnn-jp.el" (18412 33039
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-cnn-jp.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-cnn-jp" '("shimbun-cnn-jp-")))

;;;***

;;;### (autoloads nil "sb-coldsync" "shimbun/sb-coldsync.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-coldsync.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-coldsync" '("shimbun-coldsync-")))

;;;***

;;;### (autoloads nil "sb-debian" "shimbun/sb-debian.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-debian.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-debian" '("shimbun-debian-")))

;;;***

;;;### (autoloads nil "sb-debian-jp" "shimbun/sb-debian-jp.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-debian-jp.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-debian-jp" '("shimbun-debian-jp-")))

;;;***

;;;### (autoloads nil "sb-debugmagazin-de" "shimbun/sb-debugmagazin-de.el"
;;;;;;  (19101 52640 0 0))
;;; Generated autoloads from shimbun/sb-debugmagazin-de.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-debugmagazin-de" '("shimbun-debugmagazin-de-")))

;;;***

;;;### (autoloads nil "sb-dennou" "shimbun/sb-dennou.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-dennou.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-dennou" '("shimbun-dennou-")))

;;;***

;;;### (autoloads nil "sb-digiko" "shimbun/sb-digiko.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-digiko.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-digiko" '("shimbun-digiko-")))

;;;***

;;;### (autoloads nil "sb-elips" "shimbun/sb-elips.el" (18411 34945
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-elips.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-elips" '("shimbun-elips-")))

;;;***

;;;### (autoloads nil "sb-emacs-w3m" "shimbun/sb-emacs-w3m.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-emacs-w3m.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-emacs-w3m" '("shimbun-emacs-w3m-")))

;;;***

;;;### (autoloads nil "sb-emacswiki" "shimbun/sb-emacswiki.el" (17322
;;;;;;  15555 0 0))
;;; Generated autoloads from shimbun/sb-emacswiki.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-emacswiki" '("shimbun-emacswiki-")))

;;;***

;;;### (autoloads nil "sb-engadget-ja" "shimbun/sb-engadget-ja.el"
;;;;;;  (18197 61166 0 0))
;;; Generated autoloads from shimbun/sb-engadget-ja.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-engadget-ja" '("shimbun-engadget-ja-")))

;;;***

;;;### (autoloads nil "sb-excite" "shimbun/sb-excite.el" (19666 14148
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-excite.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-excite" '("shimbun-excite-")))

;;;***

;;;### (autoloads nil "sb-exconn" "shimbun/sb-exconn.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-exconn.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-exconn" '("shimbun-exconn-")))

;;;***

;;;### (autoloads nil "sb-f1fan" "shimbun/sb-f1fan.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-f1fan.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-f1fan" '("shimbun-f1fan-")))

;;;***

;;;### (autoloads nil "sb-fau" "shimbun/sb-fau.el" (17885 25587 0
;;;;;;  0))
;;; Generated autoloads from shimbun/sb-fau.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-fau" '("shimbun-fau-")))

;;;***

;;;### (autoloads nil "sb-ffii" "shimbun/sb-ffii.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-ffii.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-ffii" '("shimbun-ffii-")))

;;;***

;;;### (autoloads nil "sb-fml" "shimbun/sb-fml.el" (19277 6898 0
;;;;;;  0))
;;; Generated autoloads from shimbun/sb-fml.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-fml" '("shimbun-fml-parse-time")))

;;;***

;;;### (autoloads nil "sb-geocrawler" "shimbun/sb-geocrawler.el"
;;;;;;  (22866 65017 0 0))
;;; Generated autoloads from shimbun/sb-geocrawler.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-geocrawler" '("shimbun-geocrawler-")))

;;;***

;;;### (autoloads nil "sb-gnome" "shimbun/sb-gnome.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-gnome.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-gnome" '("shimbun-gnome-")))

;;;***

;;;### (autoloads nil "sb-haiku-os" "shimbun/sb-haiku-os.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-haiku-os.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-haiku-os" '("shimbun-haiku-os-group-alist")))

;;;***

;;;### (autoloads nil "sb-hash" "shimbun/sb-hash.el" (18904 40021
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-hash.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-hash" '("content-hash-")))

;;;***

;;;### (autoloads nil "sb-heise" "shimbun/sb-heise.el" (19146 28796
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-heise.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-heise" '("shimbun-heise-")))

;;;***

;;;### (autoloads nil "sb-hns" "shimbun/sb-hns.el" (18197 61166 0
;;;;;;  0))
;;; Generated autoloads from shimbun/sb-hns.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-hns" '("shimbun-hns-")))

;;;***

;;;### (autoloads nil "sb-ibm-dev" "shimbun/sb-ibm-dev.el" (19666
;;;;;;  14148 0 0))
;;; Generated autoloads from shimbun/sb-ibm-dev.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-ibm-dev" '("shimbun-ibm-dev-")))

;;;***

;;;### (autoloads nil "sb-impress" "shimbun/sb-impress.el" (19123
;;;;;;  18358 0 0))
;;; Generated autoloads from shimbun/sb-impress.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-impress" '("shimbun-impress-")))

;;;***

;;;### (autoloads nil "sb-infoshop" "shimbun/sb-infoshop.el" (18222
;;;;;;  31769 0 0))
;;; Generated autoloads from shimbun/sb-infoshop.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-infoshop" '("shimbun-infoshop-")))

;;;***

;;;### (autoloads nil "sb-itmedia" "shimbun/sb-itmedia.el" (20927
;;;;;;  45354 0 0))
;;; Generated autoloads from shimbun/sb-itmedia.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-itmedia" '("shimbun-itmedia-")))

;;;***

;;;### (autoloads nil "sb-japantimes" "shimbun/sb-japantimes.el"
;;;;;;  (18197 61166 0 0))
;;; Generated autoloads from shimbun/sb-japantimes.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-japantimes" '("shimbun-japantimes-")))

;;;***

;;;### (autoloads nil "sb-javaconf" "shimbun/sb-javaconf.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-javaconf.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-javaconf" '("shimbun-javaconf-")))

;;;***

;;;### (autoloads nil "sb-jpilot" "shimbun/sb-jpilot.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-jpilot.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-jpilot" '("shimbun-jpilot-")))

;;;***

;;;### (autoloads nil "sb-jpo" "shimbun/sb-jpo.el" (18197 61166 0
;;;;;;  0))
;;; Generated autoloads from shimbun/sb-jpo.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-jpo" '("shimbun-jpo-")))

;;;***

;;;### (autoloads nil "sb-kantei" "shimbun/sb-kantei.el" (20358 34828
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-kantei.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-kantei" '("shimbun-kantei-")))

;;;***

;;;### (autoloads nil "sb-kde" "shimbun/sb-kde.el" (18197 61166 0
;;;;;;  0))
;;; Generated autoloads from shimbun/sb-kde.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-kde" '("shimbun-kde-")))

;;;***

;;;### (autoloads nil "sb-kyoko-np" "shimbun/sb-kyoko-np.el" (23124
;;;;;;  5879 0 0))
;;; Generated autoloads from shimbun/sb-kyoko-np.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-kyoko-np" '("shimbun-kyoko-np-")))

;;;***

;;;### (autoloads nil "sb-laut-de" "shimbun/sb-laut-de.el" (19666
;;;;;;  14148 0 0))
;;; Generated autoloads from shimbun/sb-laut-de.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-laut-de" '("shimbun-laut-de-")))

;;;***

;;;### (autoloads nil "sb-linuxce-jp" "shimbun/sb-linuxce-jp.el"
;;;;;;  (18197 61166 0 0))
;;; Generated autoloads from shimbun/sb-linuxce-jp.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-linuxce-jp" '("shimbun-linuxce-jp-")))

;;;***

;;;### (autoloads nil "sb-lotusex" "shimbun/sb-lotusex.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-lotusex.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-lotusex" '("shimbun-lotusex-")))

;;;***

;;;### (autoloads nil "sb-lump" "shimbun/sb-lump.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-lump.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-lump" '("shimbun-lump-")))

;;;***

;;;### (autoloads nil "sb-m17n" "shimbun/sb-m17n.el" (18951 31943
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-m17n.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-m17n" '("shimbun-m17n-")))

;;;***

;;;### (autoloads nil "sb-macosx-jp" "shimbun/sb-macosx-jp.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-macosx-jp.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-macosx-jp" '("shimbun-macosx-jp-")))

;;;***

;;;### (autoloads nil "sb-mailman" "shimbun/sb-mailman.el" (20383
;;;;;;  32319 0 0))
;;; Generated autoloads from shimbun/sb-mailman.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-mailman" '("shimbun-mailman-")))

;;;***

;;;### (autoloads nil "sb-mainichi" "shimbun/sb-mainichi.el" (23328
;;;;;;  40943 0 0))
;;; Generated autoloads from shimbun/sb-mainichi.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-mainichi" '("shimbun-mainichi-")))

;;;***

;;;### (autoloads nil "sb-makanai" "shimbun/sb-makanai.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-makanai.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-makanai" '("shimbun-makanai-")))

;;;***

;;;### (autoloads nil "sb-marc-aims" "shimbun/sb-marc-aims.el" (22866
;;;;;;  65017 0 0))
;;; Generated autoloads from shimbun/sb-marc-aims.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-marc-aims" '("shimbun-marc-aims-")))

;;;***

;;;### (autoloads nil "sb-meadow" "shimbun/sb-meadow.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-meadow.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-meadow" '("shimbun-meadow-")))

;;;***

;;;### (autoloads nil "sb-mew" "shimbun/sb-mew.el" (18197 61166 0
;;;;;;  0))
;;; Generated autoloads from shimbun/sb-mew.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-mew" '("shimbun-mew-")))

;;;***

;;;### (autoloads nil "sb-mhonarc" "shimbun/sb-mhonarc.el" (18964
;;;;;;  36507 0 0))
;;; Generated autoloads from shimbun/sb-mhonarc.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-mhonarc" '("shimbun-mhonarc-")))

;;;***

;;;### (autoloads nil "sb-mozilla-jp" "shimbun/sb-mozilla-jp.el"
;;;;;;  (18197 61166 0 0))
;;; Generated autoloads from shimbun/sb-mozilla-jp.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-mozilla-jp" '("shimbun-mozilla-jp-")))

;;;***

;;;### (autoloads nil "sb-msdn" "shimbun/sb-msdn.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-msdn.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-msdn" '("shimbun-msdn-")))

;;;***

;;;### (autoloads nil "sb-msports-nifty" "shimbun/sb-msports-nifty.el"
;;;;;;  (18197 61166 0 0))
;;; Generated autoloads from shimbun/sb-msports-nifty.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-msports-nifty" '("shimbun-msports-nifty-")))

;;;***

;;;### (autoloads nil "sb-multi" "shimbun/sb-multi.el" (19887 43867
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-multi.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-multi" '("shimbun-multi-")))

;;;***

;;;### (autoloads nil "sb-n24-de" "shimbun/sb-n24-de.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-n24-de.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-n24-de" '("shimbun-n24-de-")))

;;;***

;;;### (autoloads nil "sb-namazu" "shimbun/sb-namazu.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-namazu.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-namazu" '("shimbun-namazu-")))

;;;***

;;;### (autoloads nil "sb-netbsd" "shimbun/sb-netbsd.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-netbsd.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-netbsd" '("shimbun-netbsd-")))

;;;***

;;;### (autoloads nil "sb-nikkangendai" "shimbun/sb-nikkangendai.el"
;;;;;;  (22264 56956 0 0))
;;; Generated autoloads from shimbun/sb-nikkangendai.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-nikkangendai" '("shimbun-nikkangendai-")))

;;;***

;;;### (autoloads nil "sb-nikkansports" "shimbun/sb-nikkansports.el"
;;;;;;  (22906 52141 0 0))
;;; Generated autoloads from shimbun/sb-nikkansports.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-nikkansports" '("shimbun-nikkansports-")))

;;;***

;;;### (autoloads nil "sb-nikkei" "shimbun/sb-nikkei.el" (22906 52141
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-nikkei.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-nikkei" '("shimbun-nikkei-")))

;;;***

;;;### (autoloads nil "sb-nytimes" "shimbun/sb-nytimes.el" (19666
;;;;;;  14148 0 0))
;;; Generated autoloads from shimbun/sb-nytimes.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-nytimes" '("shimbun-nytimes-")))

;;;***

;;;### (autoloads nil "sb-opentechpress-jp" "shimbun/sb-opentechpress-jp.el"
;;;;;;  (19666 14148 0 0))
;;; Generated autoloads from shimbun/sb-opentechpress-jp.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-opentechpress-jp" '("shimbun-opentechpress-jp-")))

;;;***

;;;### (autoloads nil "sb-orca" "shimbun/sb-orca.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-orca.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-orca" '("shimbun-orca-")))

;;;***

;;;### (autoloads nil "sb-palmfan" "shimbun/sb-palmfan.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-palmfan.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-palmfan" '("shimbun-palmfan-")))

;;;***

;;;### (autoloads nil "sb-pcweb-column" "shimbun/sb-pcweb-column.el"
;;;;;;  (18197 61166 0 0))
;;; Generated autoloads from shimbun/sb-pcweb-column.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-pcweb-column" '("shimbun-pcweb-column-")))

;;;***

;;;### (autoloads nil "sb-perlentaucher-de" "shimbun/sb-perlentaucher-de.el"
;;;;;;  (19666 14148 0 0))
;;; Generated autoloads from shimbun/sb-perlentaucher-de.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-perlentaucher-de" '("shimbun-perlentaucher-de-")))

;;;***

;;;### (autoloads nil "sb-pilot-link" "shimbun/sb-pilot-link.el"
;;;;;;  (18197 61166 0 0))
;;; Generated autoloads from shimbun/sb-pilot-link.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-pilot-link" '("shimbun-pilot-link-")))

;;;***

;;;### (autoloads nil "sb-pilot-mailsync" "shimbun/sb-pilot-mailsync.el"
;;;;;;  (18197 61166 0 0))
;;; Generated autoloads from shimbun/sb-pilot-mailsync.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-pilot-mailsync" '("shimbun-pilot-mailsync-")))

;;;***

;;;### (autoloads nil "sb-plucker" "shimbun/sb-plucker.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-plucker.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-plucker" '("shimbun-plucker-")))

;;;***

;;;### (autoloads nil "sb-pocketgames" "shimbun/sb-pocketgames.el"
;;;;;;  (18319 59132 0 0))
;;; Generated autoloads from shimbun/sb-pocketgames.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-pocketgames" '("shimbun-pocketgames-")))

;;;***

;;;### (autoloads nil "sb-rakuten" "shimbun/sb-rakuten.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-rakuten.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-rakuten" '("shimbun-rakuten-")))

;;;***

;;;### (autoloads nil "sb-redhat" "shimbun/sb-redhat.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-redhat.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-redhat" '("shimbun-redhat-")))

;;;***

;;;### (autoloads nil "sb-rediff" "shimbun/sb-rediff.el" (19666 14148
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-rediff.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-rediff" '("shimbun-rediff-")))

;;;***

;;;### (autoloads nil "sb-rss" "shimbun/sb-rss.el" (20874 58849 0
;;;;;;  0))
;;; Generated autoloads from shimbun/sb-rss.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-rss" '("shimbun-rss-")))

;;;***

;;;### (autoloads nil "sb-rss-blogs" "shimbun/sb-rss-blogs.el" (19343
;;;;;;  9641 0 0))
;;; Generated autoloads from shimbun/sb-rss-blogs.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-rss-blogs" '("sb-rss-blogs-guess-type-from-rss" "shimbun-rss-blogs-")))

;;;***

;;;### (autoloads nil "sb-rss-hash" "shimbun/sb-rss-hash.el" (19888
;;;;;;  58288 0 0))
;;; Generated autoloads from shimbun/sb-rss-hash.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-rss-hash" '("shimbun-rss-hash-group-path-alist")))

;;;***

;;;### (autoloads nil "sb-ruby" "shimbun/sb-ruby.el" (18964 36507
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-ruby.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-ruby" '("shimbun-ruby-")))

;;;***

;;;### (autoloads nil "sb-sankei" "shimbun/sb-sankei.el" (23528 52766
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-sankei.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-sankei" '("shimbun-sankei-")))

;;;***

;;;### (autoloads nil "sb-savannah" "shimbun/sb-savannah.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-savannah.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-savannah" '("shimbun-savannah-")))

;;;***

;;;### (autoloads nil "sb-scipy" "shimbun/sb-scipy.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-scipy.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-scipy" '("shimbun-scipy-")))

;;;***

;;;### (autoloads nil "sb-security-memo" "shimbun/sb-security-memo.el"
;;;;;;  (18197 61166 0 0))
;;; Generated autoloads from shimbun/sb-security-memo.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-security-memo" '("shimbun-security-memo-")))

;;;***

;;;### (autoloads nil "sb-slashdot" "shimbun/sb-slashdot.el" (19058
;;;;;;  58637 0 0))
;;; Generated autoloads from shimbun/sb-slashdot.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-slashdot" '("shimbun-slashdot-")))

;;;***

;;;### (autoloads nil "sb-slashdot-jp" "shimbun/sb-slashdot-jp.el"
;;;;;;  (22866 65017 0 0))
;;; Generated autoloads from shimbun/sb-slashdot-jp.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-slashdot-jp" '("shimbun-slashdot-jp-")))

;;;***

;;;### (autoloads nil "sb-sml" "shimbun/sb-sml.el" (18197 61166 0
;;;;;;  0))
;;; Generated autoloads from shimbun/sb-sml.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-sml" '("shimbun-sml-")))

;;;***

;;;### (autoloads nil "sb-sourceforge-jp" "shimbun/sb-sourceforge-jp.el"
;;;;;;  (22866 65017 0 0))
;;; Generated autoloads from shimbun/sb-sourceforge-jp.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-sourceforge-jp" '("shimbun-sourceforge-jp-")))

;;;***

;;;### (autoloads nil "sb-spiegel" "shimbun/sb-spiegel.el" (18369
;;;;;;  20029 0 0))
;;; Generated autoloads from shimbun/sb-spiegel.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-spiegel" '("shimbun-spiegel-")))

;;;***

;;;### (autoloads nil "sb-sponichi" "shimbun/sb-sponichi.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-sponichi.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-sponichi" '("shimbun-sponichi-")))

;;;***

;;;### (autoloads nil "sb-squeak-dev" "shimbun/sb-squeak-dev.el"
;;;;;;  (18197 61166 0 0))
;;; Generated autoloads from shimbun/sb-squeak-dev.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-squeak-dev" '("shimbun-squeak-dev-")))

;;;***

;;;### (autoloads nil "sb-squeak-ja" "shimbun/sb-squeak-ja.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-squeak-ja.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-squeak-ja" '("shimbun-squeak-ja-")))

;;;***

;;;### (autoloads nil "sb-sueddeutsche-de" "shimbun/sb-sueddeutsche-de.el"
;;;;;;  (19666 14148 0 0))
;;; Generated autoloads from shimbun/sb-sueddeutsche-de.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-sueddeutsche-de" '("shimbun-sueddeutsche-de-")))

;;;***

;;;### (autoloads nil "sb-tcup" "shimbun/sb-tcup.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-tcup.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-tcup" '("shimbun-tcup-")))

;;;***

;;;### (autoloads nil "sb-tdiary" "shimbun/sb-tdiary.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-tdiary.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-tdiary" '("shimbun-tdiary-")))

;;;***

;;;### (autoloads nil "sb-tdiary-ml" "shimbun/sb-tdiary-ml.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-tdiary-ml.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-tdiary-ml" '("shimbun-tdiary-ml-")))

;;;***

;;;### (autoloads nil "sb-tech-on" "shimbun/sb-tech-on.el" (19988
;;;;;;  9343 0 0))
;;; Generated autoloads from shimbun/sb-tech-on.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-tech-on" '("shimbun-tech-on-")))

;;;***

;;;### (autoloads nil "sb-texfaq" "shimbun/sb-texfaq.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-texfaq.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-texfaq" '("shimbun-texfaq-")))

;;;***

;;;### (autoloads nil "sb-text" "shimbun/sb-text.el" (18964 36507
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-text.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-text" '("shimbun-")))

;;;***

;;;### (autoloads nil "sb-the-onion" "shimbun/sb-the-onion.el" (17654
;;;;;;  34465 0 0))
;;; Generated autoloads from shimbun/sb-the-onion.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-the-onion" '("shimbun-the-onion-")))

;;;***

;;;### (autoloads nil "sb-the-register" "shimbun/sb-the-register.el"
;;;;;;  (18537 33443 0 0))
;;; Generated autoloads from shimbun/sb-the-register.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-the-register" '("shimbun-the-register-")))

;;;***

;;;### (autoloads nil "sb-tigris" "shimbun/sb-tigris.el" (22866 65017
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-tigris.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-tigris" '("shimbun-tigris-")))

;;;***

;;;### (autoloads nil "sb-toshiba" "shimbun/sb-toshiba.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-toshiba.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-toshiba" '("shimbun-toshiba-")))

;;;***

;;;### (autoloads nil "sb-vinelinux" "shimbun/sb-vinelinux.el" (18964
;;;;;;  36507 0 0))
;;; Generated autoloads from shimbun/sb-vinelinux.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-vinelinux" '("shimbun-vinelinux-")))

;;;***

;;;### (autoloads nil "sb-w3m-dev" "shimbun/sb-w3m-dev.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-w3m-dev.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-w3m-dev" '("shimbun-w3m-dev-")))

;;;***

;;;### (autoloads nil "sb-welt-de" "shimbun/sb-welt-de.el" (19666
;;;;;;  14148 0 0))
;;; Generated autoloads from shimbun/sb-welt-de.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-welt-de" '("shimbun-welt-de-")))

;;;***

;;;### (autoloads nil "sb-wiki" "shimbun/sb-wiki.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-wiki.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-wiki" '("shimbun-wiki-group-alist")))

;;;***

;;;### (autoloads nil "sb-wikimedia" "shimbun/sb-wikimedia.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-wikimedia.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-wikimedia" '("shimbun-wikimedia-")))

;;;***

;;;### (autoloads nil "sb-wincefan" "shimbun/sb-wincefan.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-wincefan.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-wincefan" '("shimbun-wincefan-")))

;;;***

;;;### (autoloads nil "sb-wired-jp" "shimbun/sb-wired-jp.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-wired-jp.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-wired-jp" '("shimbun-wired-jp-")))

;;;***

;;;### (autoloads nil "sb-x51" "shimbun/sb-x51.el" (19666 14148 0
;;;;;;  0))
;;; Generated autoloads from shimbun/sb-x51.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-x51" '("shimbun-x51-")))

;;;***

;;;### (autoloads nil "sb-xemacs" "shimbun/sb-xemacs.el" (18197 61166
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-xemacs.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-xemacs" '("shimbun-xemacs-")))

;;;***

;;;### (autoloads nil "sb-yahoo" "shimbun/sb-yahoo.el" (19676 50313
;;;;;;  0 0))
;;; Generated autoloads from shimbun/sb-yahoo.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-yahoo" '("shimbun-yahoo-")))

;;;***

;;;### (autoloads nil "sb-yahoo-auctions" "shimbun/sb-yahoo-auctions.el"
;;;;;;  (20927 43682 0 0))
;;; Generated autoloads from shimbun/sb-yahoo-auctions.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-yahoo-auctions" '("shimbun-yahoo-auctions-")))

;;;***

;;;### (autoloads nil "sb-yahoo-sports" "shimbun/sb-yahoo-sports.el"
;;;;;;  (18197 61166 0 0))
;;; Generated autoloads from shimbun/sb-yahoo-sports.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-yahoo-sports" '("shimbun-yahoo-sports-")))

;;;***

;;;### (autoloads nil "sb-yomiuri" "shimbun/sb-yomiuri.el" (22906
;;;;;;  52141 0 0))
;;; Generated autoloads from shimbun/sb-yomiuri.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-yomiuri" '("shimbun-yomiuri-")))

;;;***

;;;### (autoloads nil "sb-yomiuri-html" "shimbun/sb-yomiuri-html.el"
;;;;;;  (18197 61166 0 0))
;;; Generated autoloads from shimbun/sb-yomiuri-html.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-yomiuri-html" '("shimbun-yomiuri-html-prefer-text-plain")))

;;;***

;;;### (autoloads nil "sb-yoshirin" "shimbun/sb-yoshirin.el" (22517
;;;;;;  57034 0 0))
;;; Generated autoloads from shimbun/sb-yoshirin.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-yoshirin" '("shimbun-yoshirin-")))

;;;***

;;;### (autoloads nil "sb-zdnet-jp" "shimbun/sb-zdnet-jp.el" (18197
;;;;;;  61166 0 0))
;;; Generated autoloads from shimbun/sb-zdnet-jp.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-zdnet-jp" '("shimbun-zdnet-jp-")))

;;;***

;;;### (autoloads nil "sb-zeit-de" "shimbun/sb-zeit-de.el" (19666
;;;;;;  14148 0 0))
;;; Generated autoloads from shimbun/sb-zeit-de.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "sb-zeit-de" '("shimbun-zeit-de-")))

;;;***

;;;### (autoloads nil "shimbun" "shimbun/shimbun.el" (23497 10629
;;;;;;  0 0))
;;; Generated autoloads from shimbun/shimbun.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "shimbun" '("shimbun-")))

;;;***

;;;### (autoloads nil "w3m" "w3m.el" (23501 36967 0 0))
;;; Generated autoloads from w3m.el

(autoload 'w3m-retrieve "w3m" "\
Retrieve web contents pointed to by URL.
It will put the retrieved contents into the current buffer.

If HANDLER is nil, this function will retrieve web contents, return
the content type of the retrieved data, and then come to an end.  This
behavior is what is called a synchronous operation.  You have to
specify HANDLER in order to make this function show its real ability,
which is called an asynchronous operation.

If HANDLER is a function, this function will come to an end in no time.
In this case, contents will be retrieved by the asynchronous process
after a while.  And after finishing retrieving contents successfully,
HANDLER will be called on the buffer where this function starts.  The
content type of the retrieved data will be passed to HANDLER as a
string argument.

NO-UNCOMPRESS specifies whether this function should not uncompress contents.
NO-CACHE specifies whether this function should not use cached contents.
POST-DATA and REFERER will be sent to the web server with a request.

\(fn URL &optional NO-UNCOMPRESS NO-CACHE POST-DATA REFERER HANDLER)" nil nil)

(autoload 'w3m-download "w3m" "\
Download contents of URL to a file named FILENAME.
NO-CACHE (which the prefix argument gives when called interactively)
specifies not using the cached data.

\(fn &optional URL FILENAME NO-CACHE HANDLER POST-DATA)" t nil)

(autoload 'w3m-goto-url "w3m" "\
Visit World Wide Web pages in the current buffer.

This is the primitive function of `w3m'.

If the second argument RELOAD is non-nil, reload a content of URL.
Except that if it is 'redisplay, re-display the page without reloading.
The third argument CHARSET specifies a charset to be used for decoding
a content.
The fourth argument POST-DATA should be a string or a cons cell.
If it is a string, it makes this function request a body as if
the content-type is \"x-www-form-urlencoded\".  If it is a cons cell,
the car of a cell is used as the content-type and the cdr of a cell is
used as the body.
If the fifth argument REFERER is specified, it is used for a Referer:
field for this request.
The remaining HANDLER, ELEMENT[1], NO-POPUP, and SAVE-POS[2] are for
the internal operations of emacs-w3m.
You can also use \"quicksearch\" url schemes such as \"gg:emacs\" which
would search for the term \"emacs\" with the Google search engine.
See the `w3m-search' function and the variable `w3m-uri-replace-alist'.

Notes for the developers:
\[1] ELEMENT is a history element which has already been registered in
the `w3m-history-flat' variable.  It is corresponding to URL to be
retrieved at this time, not for the url of the current page.

\[2] SAVE-POS leads this function to save the current emacs-w3m window
configuration; i.e. to run `w3m-history-store-position'.
`w3m-history-store-position' should be called in a w3m-mode buffer, so
this will be convenient if a command that calls this function may be
invoked in other than a w3m-mode buffer.

\(fn URL &optional RELOAD CHARSET POST-DATA REFERER HANDLER ELEMENT NO-POPUP SAVE-POS)" t nil)

(autoload 'w3m-goto-url-new-session "w3m" "\
Visit World Wide Web pages in a new buffer.

If you invoke this command in the emacs-w3m buffer, the new buffer
will be created by copying the current buffer.  Otherwise, the new
buffer will start afresh.

\(fn URL &optional RELOAD CHARSET POST-DATA REFERER)" t nil)

(autoload 'w3m-gohome "w3m" "\
Go to the Home page.

\(fn)" t nil)

(autoload 'w3m-create-empty-session "w3m" "\
Create an empty page as a new session and visit it.

\(fn)" t nil)

(autoload 'w3m "w3m" "\
Visit World Wide Web pages using the external w3m command.

If no emacs-w3m session already exists: If POINT is at a url
string, visit that. Otherwise, if `w3m-home-page' is defined,
visit that. Otherwise, present a blank page. This behavior can be
over-ridden by setting variable `w3m-quick-start' to nil, in
which case you will always be prompted for a URL.

If an emacs-w3m session already exists: Pop to one of its windows
or frames. You can over-ride this behavior by setting
`w3m-quick-start' to nil, in order to always be prompted for a
URL.

In you have set `w3m-quick-start' to nil, but wish to over-ride
default behavior from the command line, either run this command
with a prefix argument or enter the empty string for the prompt.
In such cases, this command will visit a url at the point or,
lacking that, the URL set in variable `w3m-home-page' or, lacking
that, the \"about:\" page.

Any of five display styles are possible. See `w3m-display-mode'
for a description of those options.

You can also run this command in the batch mode as follows:

  emacs -f w3m http://emacs-w3m.namazu.org/ &

In that case, or if this command is called non-interactively, the
variables `w3m-pop-up-windows' and `w3m-pop-up-frames' will be ignored
\(treated as nil) and it will run emacs-w3m at the current (or the
initial) window.

If the optional NEW-SESSION is non-nil, this function creates a new
emacs-w3m buffer.  Besides that, it also makes a new emacs-w3m buffer
if `w3m-make-new-session' is non-nil and a user specifies a url string.

The optional INTERACTIVE-P is for the internal use; it is mainly used
to check whether Emacs 22 or later calls this function as an
interactive command in the batch mode.

\(fn &optional URL NEW-SESSION INTERACTIVE-P)" t nil)

(autoload 'w3m-browse-url "w3m" "\
Ask emacs-w3m to browse URL.
NEW-SESSION specifies whether to create a new emacs-w3m session.  URL
defaults to the string looking like a url around the cursor position.

\(fn URL &optional NEW-SESSION)" t nil)

(autoload 'w3m-find-file "w3m" "\
Function used to open FILE whose name is expressed in ordinary format.
The file name will be converted into the file: scheme.

\(fn FILE)" t nil)

(autoload 'w3m-region "w3m" "\
Render the region of the current buffer between START and END.
URL specifies the address where the contents come from.  It can be
omitted or nil when the address is not identified.  CHARSET is used
for decoding the contents.  If it is nil, this function attempts to
parse the meta tag to extract the charset.

\(fn START END &optional URL CHARSET)" t nil)

(autoload 'w3m-buffer "w3m" "\
Render the current buffer.
See `w3m-region' for the optional arguments.

\(fn &optional URL CHARSET)" t nil)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m" '("w3m-" "emacs-w3m-version")))

;;;***

;;;### (autoloads nil "w3m-antenna" "w3m-antenna.el" (22866 65015
;;;;;;  0 0))
;;; Generated autoloads from w3m-antenna.el

(autoload 'w3m-about-antenna "w3m-antenna" "\


\(fn URL &optional NO-DECODE NO-CACHE POST-DATA REFERER HANDLER)" nil nil)

(autoload 'w3m-antenna "w3m-antenna" "\
Report changes of WEB sites, which is specified in `w3m-antenna-sites'.

\(fn &optional NO-CACHE)" t nil)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-antenna" '("w3m-antenna-")))

;;;***

;;;### (autoloads nil "w3m-bookmark" "w3m-bookmark.el" (23086 2541
;;;;;;  0 0))
;;; Generated autoloads from w3m-bookmark.el

(autoload 'w3m-bookmark-add-this-url "w3m-bookmark" "\
Add link under cursor to bookmark.

\(fn)" t nil)

(autoload 'w3m-bookmark-add-current-url "w3m-bookmark" "\
Add a url of the current page to the bookmark.
With prefix, ask for a new url instead of the present one.

\(fn &optional ARG)" t nil)

(autoload 'w3m-bookmark-add-all-urls "w3m-bookmark" "\
Add urls of all pages being visited to the bookmark.

\(fn)" t nil)

(autoload 'w3m-bookmark-add-current-url-group "w3m-bookmark" "\
Add link of the group of current urls to the bookmark.

\(fn)" t nil)

(autoload 'w3m-bookmark-view "w3m-bookmark" "\
Display the bookmark list in the current buffer.

\(fn &optional RELOAD)" t nil)

(autoload 'w3m-bookmark-view-new-session "w3m-bookmark" "\
Display the bookmark list in a new buffer.

\(fn &optional RELOAD)" t nil)

(autoload 'w3m-about-bookmark "w3m-bookmark" "\


\(fn &rest ARGS)" nil nil)

(autoload 'w3m-setup-bookmark-menu "w3m-bookmark" "\
Setup w3m bookmark items in menubar.

\(fn)" nil nil)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-bookmark" '("w3m-bookmark-")))

;;;***

;;;### (autoloads nil "w3m-bug" "w3m-bug.el" (19277 6908 0 0))
;;; Generated autoloads from w3m-bug.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-bug" '("report-emacs-w3m-bug")))

;;;***

;;;### (autoloads nil "w3m-ccl" "w3m-ccl.el" (19997 17287 0 0))
;;; Generated autoloads from w3m-ccl.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-ccl" '("w3m-")))

;;;***

;;;### (autoloads nil "w3m-cookie" "w3m-cookie.el" (23181 5729 0
;;;;;;  0))
;;; Generated autoloads from w3m-cookie.el

(autoload 'w3m-cookie-shutdown "w3m-cookie" "\
Save cookies, and reset cookies' data.

\(fn &optional INTERACTIVE-P)" t nil)

(autoload 'w3m-cookie-set "w3m-cookie" "\
Register cookies which correspond to URL.
BEG and END should be an HTTP response header region on current buffer.

\(fn URL BEG END)" nil nil)

(autoload 'w3m-cookie-get "w3m-cookie" "\
Get a cookie field string which corresponds to the URL.

\(fn URL)" nil nil)

(autoload 'w3m-cookie "w3m-cookie" "\
Display cookies and enable you to manage them.

\(fn &optional NO-CACHE)" t nil)

(autoload 'w3m-about-cookie "w3m-cookie" "\
Make the html contents to display and to enable you to manage cookies.
To delete all cookies associated with amazon.com for example, do it in
the following two steps:

1. Mark them `unused' (type `C-c C-c' or press any OK button).

Limit to [amazon.com          ] <= [ ]regexp  [OK]
\( )Noop  ( )Use all  (*)Unuse all  ( )Delete unused all  [OK]

2. Delete cookies that are marked `unused'.

Limit to [amazon.com          ] <= [ ]regexp  [OK]
\( )Noop  ( )Use all  ( )Unuse all  (*)Delete unused all  [OK]

You can mark cookies on the one-by-one basis of course.  The `Limit-to'
string is case insensitive and allows a regular expression.

\(fn URL &optional NO-DECODE NO-CACHE POST-DATA &rest ARGS)" nil nil)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-cookie" '("w3m-")))

;;;***

;;;### (autoloads nil "w3m-dtree" "w3m-dtree.el" (22866 65015 0 0))
;;; Generated autoloads from w3m-dtree.el

(autoload 'w3m-about-dtree "w3m-dtree" "\


\(fn URL &optional NODECODE ALLFILES &rest ARGS)" nil nil)

(autoload 'w3m-dtree "w3m-dtree" "\
Display directory tree on local file system.
If called with 'prefix argument', display all directorys and files.

\(fn ALLFILES PATH)" t nil)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-dtree" '("w3m-dtree-")))

;;;***

;;;### (autoloads nil "w3m-ems" "w3m-ems.el" (23188 63847 0 0))
;;; Generated autoloads from w3m-ems.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-ems" '("w3m-")))

;;;***

;;;### (autoloads nil "w3m-favicon" "w3m-favicon.el" (23320 55355
;;;;;;  0 0))
;;; Generated autoloads from w3m-favicon.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-favicon" '("w3m-")))

;;;***

;;;### (autoloads nil "w3m-fb" "w3m-fb.el" (23292 52595 0 0))
;;; Generated autoloads from w3m-fb.el

(defvar w3m-fb-mode nil "\
Non-nil if W3m-Fb mode is enabled.
See the `w3m-fb-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `w3m-fb-mode'.")

(custom-autoload 'w3m-fb-mode "w3m-fb" nil)

(autoload 'w3m-fb-mode "w3m-fb" "\
Toggle W3M Frame Buffer mode.
This allows frame-local lists of buffers (tabs).

\(fn &optional ARG)" t nil)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-fb" '("w3m-fb-")))

;;;***

;;;### (autoloads nil "w3m-filter" "w3m-filter.el" (23327 19052 0
;;;;;;  0))
;;; Generated autoloads from w3m-filter.el

(autoload 'w3m-filter "w3m-filter" "\
Apply filtering rule of URL against a content in this buffer.

\(fn URL)" nil nil)

(autoload 'w3m-toggle-filtering "w3m-filter" "\
Toggle whether web pages will have their html modified by w3m's filters before being rendered.
When called with a prefix argument, prompt for a single filter to
toggle with completion (a function toggled last will first appear).

\(fn ARG)" t nil)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-filter" '("w3m-filter-")))

;;;***

;;;### (autoloads nil "w3m-form" "w3m-form.el" (22959 25184 0 0))
;;; Generated autoloads from w3m-form.el

(autoload 'w3m-fontify-forms "w3m-form" "\
Process half-dumped data and fontify forms in this buffer.

\(fn)" nil nil)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-form" '("w3m-fo")))

;;;***

;;;### (autoloads nil "w3m-hist" "w3m-hist.el" (20276 52187 0 0))
;;; Generated autoloads from w3m-hist.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-hist" '("w3m-history")))

;;;***

;;;### (autoloads nil "w3m-image" "w3m-image.el" (23273 20162 0 0))
;;; Generated autoloads from w3m-image.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-image" '("w3m-")))

;;;***

;;;### (autoloads nil "w3m-lnum" "w3m-lnum.el" (22932 62997 0 0))
;;; Generated autoloads from w3m-lnum.el

(autoload 'w3m-lnum-mode "w3m-lnum" "\
Minor mode to extend point commands by using Conkeror style number selection.
With prefix ARG 0 disable battery included point functions, otherwise
enable them.  With no prefix ARG - toggle.

\(fn &optional ARG)" t nil)

(autoload 'w3m-lnum-goto "w3m-lnum" "\
Turn on link, image and form numbers and ask for one to go to.
0 corresponds to location url.

\(fn)" t nil)

(autoload 'w3m-lnum-follow "w3m-lnum" "\
Turn on link numbers, ask for one and execute appropriate action on it.
If link - visit it, when button - press, when input - activate it,
If image - toggle it.
With prefix ARG visit link in new session or don't move over
field/button/image on activation/push/toggle.
With `-' ARG, for link image - go to it and toggle it, if link,
visit in background.  With -4 ARG, for link image - toggle it.
With double prefix ARG, prompt for url to visit.
With triple prefix ARG, prompt for url to visit in new session.

\(fn ARG)" t nil)

(autoload 'w3m-lnum-universal "w3m-lnum" "\
Turn on link numbers, ask for one and offer actions over it depending on selection type.
Actions may be selected either by hitting corresponding key,
pressing <return> over the action line or left clicking.

\(fn)" t nil)

(autoload 'w3m-lnum-toggle-inline-image "w3m-lnum" "\
If image at point, toggle it.
Otherwise turn on link numbers and toggle selected image.
With prefix ARG open url under image in new session.
If no such url, move over image and toggle it.

\(fn &optional ARG)" t nil)

(autoload 'w3m-lnum-view-image "w3m-lnum" "\
Display the image under point in the external viewer.
If no image at poing, turn on image numbers and display selected.
The viewer is defined in `w3m-content-type-alist' for every type of an
image.

\(fn)" t nil)

(autoload 'w3m-lnum-save-image "w3m-lnum" "\
Save the image under point to a file.
If no image at point, turn on image numbers and save selected.
The default name will be the original name of the image.

\(fn)" t nil)

(autoload 'w3m-lnum-external-view-this-url "w3m-lnum" "\
Launch the external browser and display the link at point.
If no link at point, turn on link numbers and open selected externally.

\(fn)" t nil)

(autoload 'w3m-lnum-edit-this-url "w3m-lnum" "\
Edit the page linked from the anchor under the cursor.
If no such, turn on link numbers and edit selected.

\(fn)" t nil)

(autoload 'w3m-lnum-print-this-url "w3m-lnum" "\
Display the url under point in the echo area and put it into `kill-ring'.
If no url under point, activate numbering and select one.

\(fn)" t nil)

(autoload 'w3m-lnum-download-this-url "w3m-lnum" "\
Download the file or the page pointed to by the link under point.
If no point, activate numbering and select andchor to download.

\(fn)" t nil)

(autoload 'w3m-lnum-bookmark-add-this-url "w3m-lnum" "\
Add link under cursor to bookmarks.
If no link under point, activate numbering and ask for one.

\(fn)" t nil)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-lnum" '("w3m-")))

;;;***

;;;### (autoloads nil "w3m-mail" "w3m-mail.el" (21075 54379 0 0))
;;; Generated autoloads from w3m-mail.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-mail" '("w3m-mail")))

;;;***

;;;### (autoloads nil "w3m-namazu" "w3m-namazu.el" (22866 65015 0
;;;;;;  0))
;;; Generated autoloads from w3m-namazu.el

(autoload 'w3m-about-namazu "w3m-namazu" "\


\(fn URL &optional NO-DECODE NO-CACHE &rest ARGS)" nil nil)

(autoload 'w3m-namazu "w3m-namazu" "\
Search indexed files with Namazu.

\(fn INDEX QUERY &optional RELOAD)" t nil)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-namazu" '("w3m-namazu-")))

;;;***

;;;### (autoloads nil "w3m-perldoc" "w3m-perldoc.el" (23197 18911
;;;;;;  0 0))
;;; Generated autoloads from w3m-perldoc.el

(autoload 'w3m-about-perldoc "w3m-perldoc" "\


\(fn URL &optional NO-DECODE NO-CACHE &rest ARGS)" nil nil)

(autoload 'w3m-perldoc "w3m-perldoc" "\
View Perl documents.

\(fn DOCNAME)" t nil)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-perldoc" '("w3m-perldoc-")))

;;;***

;;;### (autoloads nil "w3m-proc" "w3m-proc.el" (23320 55340 0 0))
;;; Generated autoloads from w3m-proc.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-proc" '("w3m-process-")))

;;;***

;;;### (autoloads nil "w3m-rss" "w3m-rss.el" (20486 20998 0 0))
;;; Generated autoloads from w3m-rss.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-rss" '("w3m-rss-")))

;;;***

;;;### (autoloads nil "w3m-save" "w3m-save.el" (23086 2541 0 0))
;;; Generated autoloads from w3m-save.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-save" '("w3m-save-buffer")))

;;;***

;;;### (autoloads nil "w3m-search" "w3m-search.el" (23292 52595 0
;;;;;;  0))
;;; Generated autoloads from w3m-search.el

(autoload 'w3m-search "w3m-search" "\
Search QUERY using SEARCH-ENGINE.

Search results will appear in the current buffer.

When called interactively with a prefix argument, you can choose one of
the search engines defined in `w3m-search-engine-alist'.  Otherwise use
`w3m-search-default-engine'.
If Transient Mark mode, use the region as an initial string of query
and deactivate the mark.

\(fn SEARCH-ENGINE QUERY)" t nil)

(autoload 'w3m-search-new-session "w3m-search" "\
Like `w3m-search', but do the search in a new buffer.

\(fn SEARCH-ENGINE QUERY)" t nil)

(autoload 'w3m-search-uri-replace "w3m-search" "\
Generate query string for ENGINE from URI matched by last search.

\(fn URI ENGINE)" nil nil)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-search" '("w3m-search-")))

;;;***

;;;### (autoloads nil "w3m-session" "w3m-session.el" (23292 52595
;;;;;;  0 0))
;;; Generated autoloads from w3m-session.el

(autoload 'w3m-session-save "w3m-session" "\
Save the current session (all currently open emacs-w3m buffers).

The user will be prompted for a name for the saved session.  The
saved session information will include, for each currently open
emacs-w3m buffer: the current url and page title, and the
buffer's url history.

\(fn)" t nil)

(autoload 'w3m-session-crash-recovery-remove "w3m-session" "\
Remove crash recovery session set.

\(fn)" nil nil)

(autoload 'w3m-session-select "w3m-session" "\
Select session from session list.
Position point at N-th session if N is given.  With the
prefix-argument, toggles the position of the popup window between
being below or beside the main window.

\(fn &optional N TOGGLE NOMSG)" t nil)

(autoload 'w3m-setup-session-menu "w3m-session" "\
Setup w3m session items in menubar.

\(fn)" nil nil)

(autoload 'w3m-session-last-autosave-session "w3m-session" "\


\(fn)" nil nil)

(autoload 'w3m-session-last-crashed-session "w3m-session" "\


\(fn)" nil nil)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-session" '("w3m-")))

;;;***

;;;### (autoloads nil "w3m-symbol" "w3m-symbol.el" (22866 65015 0
;;;;;;  0))
;;; Generated autoloads from w3m-symbol.el

(autoload 'w3m-replace-symbol "w3m-symbol" "\


\(fn)" nil nil)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-symbol" '("w3m-")))

;;;***

;;;### (autoloads nil "w3m-tabmenu" "w3m-tabmenu.el" (20280 23920
;;;;;;  0 0))
;;; Generated autoloads from w3m-tabmenu.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-tabmenu" '("w3m-")))

;;;***

;;;### (autoloads nil "w3m-util" "w3m-util.el" (23292 52595 0 0))
;;; Generated autoloads from w3m-util.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-util" '("w3m-")))

;;;***

;;;### (autoloads nil "w3m-weather" "w3m-weather.el" (20486 20998
;;;;;;  0 0))
;;; Generated autoloads from w3m-weather.el

(autoload 'w3m-weather "w3m-weather" "\
Display weather report.

\(fn AREA)" t nil)

(autoload 'w3m-about-weather "w3m-weather" "\


\(fn URL NO-DECODE NO-CACHE POST-DATA REFERER HANDLER)" nil nil)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "w3m-weather" '("w3m-weather-")))

;;;***

;;; w3m-load.el ends here
